module.exports = {
  GET_AUTH_UN: 'GET_AUTH_UN',
  GET_AUTH_PW: 'GET_AUTH_PW',
  RETURN_CLEAR_UN: 'RETURN_CLEAR_UN',
  RETURN_CLEAR_PW: 'RETURN_CLEAR_PW',
  INPUT_CHANGE_UN: 'INPUT_CHANGE_UN',
  INPUT_CHANGE_PW: 'INPUT_CHANGE_PW',
  GET_DATA: 'GET_DATA',
  RETURN_CLEAR: 'RETURN_CLEAR',
  INPUT_CHANGE: 'INPUT_CHANGE',
  DECREMENT_PAGE: 'DECREMENT_PAGE',
  INCREMENT_PAGE: 'INCREMENT_PAGE'
}
